cpanm Module::Install
cpanm Git
cpanm Error
cpanm Apache::Session
cpanm CGI::Emulate::PSGI
cpanm CGI::PSGI
cpanm CSS::Squish
cpanm Class::Accessor::Fast
cpanm Convert::Color
cpanm Crypt::Eksblowfish
cpanm Crypt::SSLeay
cpanm Crypt::X509
cpanm DBIx::SearchBuilder
cpanm Data::GUID
cpanm Data::ICal
cpanm Date::Extract
cpanm Date::Manip
cpanm DateTime
cpanm DateTime::Format::Natural
cpanm DateTime::Locale
cpanm Devel::StackTrace
cpanm Email::Address
cpanm Email::Address::List
cpanm Encode::Detect::Detector
cpanm Encode::HanExtra
cpanm FCGI::ProcManager
cpanm File::ShareDir
cpanm File::Which
cpanm GnuPG::Interface
cpanm HTML::FormatExternal
cpanm HTML::FormatText::WithLinks
cpanm HTML::FormatText::WithLinks::AndTables
cpanm HTML::Gumbo
cpanm HTML::Mason
cpanm HTML::Mason::PSGIHandler
cpanm HTML::Quoted
cpanm HTML::RewriteAttributes
cpanm HTML::Scrubber
cpanm IPC::Run
cpanm JSON
cpanm Locale::Maketext::Fuzzy
cpanm Locale::Maketext::Lexicon
cpanm Locale::PO
cpanm Test::Needs~"< 0.002003"
cpanm Log::Dispatch
cpanm MIME::Entity
cpanm MIME::Types
cpanm Module::Refresh
cpanm Module::Versions::Report
cpanm Mozilla::CA
cpanm Net::CIDR
cpanm Net::LDAP
cpanm Net::LDAP::Server::Test
cpanm Net::SSL
cpanm PerlIO::eol
cpanm Plack
cpanm Plack::Handler::Starlet
cpanm Regexp::Common
cpanm Regexp::Common::net::CIDR
cpanm Regexp::IPv6
cpanm Role::Basic
cpanm Symbol::Global::Name
cpanm Text::Password::Pronounceable
cpanm Text::Quoted
cpanm Text::WikiFormat
cpanm Text::Wrapper
cpanm Time::ParseDate
cpanm Tree::Simple
cpanm UNIVERSAL::require
cpanm XML::RSS
cpanm CSS::Minifier::XS
cpanm JavaScript::Minifier::XS
cpanm Business::Hours
cpanm Data::Page::Pageset
cpanm Scope::Upper
cpanm Net::IP

cpanm Log::Dispatch::Perl
cpanm Test::Email
cpanm Test::WWW::Mechanize
cpanm Set::Tiny
cpanm GD
cpanm GraphViz
cpanm Plack::Middleware::Test::StashWarnings
cpanm Email::Abstract
cpanm Test::Pod
cpanm Mojo::DOM
cpanm XML::Simple
cpanm Test::Expect
cpanm Test::WWW::Mechanize::PSGI

# For extension development
cpanm Module::Install::RTx
cpanm Dist::Zilla::MintingProfile::RTx
